# Generated by Django 5.1.4 on 2025-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A10_Usu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
