# Generated by Django 5.1.4 on 2025-01-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A10_Usu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_consulta', models.DateTimeField(auto_now_add=True)),
                ('temperatura', models.FloatField()),
                ('p_sistolica', models.IntegerField()),
                ('p_diastolica', models.IntegerField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('diagnostico', models.TextField()),
                ('prescripcion', models.TextField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_fichas', to='A10_Usu.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_fichas', to='A10_Usu.paciente')),
            ],
            options={
                'verbose_name': 'Ficha Médica',
                'verbose_name_plural': 'Fichas Médicas',
                'ordering': ['f_consulta', 'estado'],
            },
        ),
    ]
