# Generated by Django 5.1.4 on 2025-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A30_Fic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichamedica',
            name='estado',
            field=models.CharField(choices=[('NoIniciada', 'No Iniciada'), ('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='NoIniciada', max_length=20),
        ),
    ]
