# Generated by Django 5.1.4 on 2025-01-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A30_Fic', '0002_alter_fichamedica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='sintomas',
            field=models.TextField(blank=True, default='Sin síntomas', null=True),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='altura',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fichamedica',
            name='peso',
            field=models.FloatField(default=0.0),
        ),
    ]
