# Generated by Django 5.1.4 on 2025-02-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A30_Fic', '0003_fichamedica_sintomas_alter_fichamedica_altura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='imc',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
