# Generated by Django 5.1.4 on 2025-01-07 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A10_Usu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_hra', models.DateTimeField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('tomada', 'Tomada'), ('realizada', 'Realizada'), ('anulada', 'Anulada')], default='libre', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_horas', to='A10_Usu.medico')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paciente_horas', to='A10_Usu.paciente')),
            ],
            options={
                'verbose_name': 'Hora Médica',
                'verbose_name_plural': 'Horas Médicas',
                'ordering': ['f_hra'],
            },
        ),
    ]
