# Generated by Django 5.1.4 on 2025-01-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A20_Hrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horamedica',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('tomada', 'Tomada'), ('cancelada', 'Cancelada'), ('pagada', 'Pagada'), ('realizada', 'Realizada'), ('anulada', 'Anulada')], default='libre', max_length=20),
        ),
    ]
