# Generated by Django 5.1.4 on 2025-02-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A10_Usu', '0003_alter_customuser_email'),
        ('A20_Hrs', '0002_alter_horamedica_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='horamedica',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='horamedica',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('tomada', 'Tomada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='libre', max_length=20),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta Crédito'), ('bono', 'Bono Isapre')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_bono', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_transaccion', models.CharField(blank=True, max_length=20, null=True)),
                ('hora_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='A20_Hrs.horamedica')),
                ('sistema_salud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='A10_Usu.sistemasalud')),
            ],
        ),
    ]
