# Generated by Django 5.1.4 on 2025-02-18 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A20_Hrs', '0003_horamedica_pagada_alter_horamedica_estado_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horamedica',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('tomada', 'Tomada'), ('pagada', 'Pagada'), ('iniciada', 'Iniciada'), ('anulada', 'Anulada')], default='libre', max_length=20),
        ),
    ]
