# Generated by Django 5.1.4 on 2025-02-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A20_Hrs', '0004_alter_horamedica_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horamedica',
            name='estado',
            field=models.CharField(choices=[('libre', 'Libre'), ('tomada', 'Tomada'), ('pagada', 'Pagada'), ('iniciada', 'Iniciada'), ('anulada', 'Anulada'), ('perdida', 'Perdida')], default='libre', max_length=20),
        ),
    ]
