# Generated by Django 5.1.4 on 2025-02-06 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('A20_Hrs', '0002_alter_horamedica_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_gen', models.CharField(help_text='Nombre genérico', max_length=100)),
                ('nombre_com', models.CharField(help_text='Nombre comercial', max_length=100)),
                ('forma_farma', models.CharField(help_text='Forma farmacéutica', max_length=100)),
                ('presentacion', models.CharField(help_text='Presentación', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción', null=True)),
                ('archivo', models.FileField(blank=True, help_text='Ficha técnica', null=True, upload_to='Medicamentos')),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_gen'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('p_sistolica', models.IntegerField()),
                ('p_diastolica', models.IntegerField()),
                ('altura', models.FloatField(default=0.0)),
                ('peso', models.FloatField(default=0.0)),
                ('imc', models.FloatField(blank=True, default=0.0, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('sintomas', models.TextField(blank=True, default='Sin síntomas', null=True)),
                ('diagnostico', models.TextField()),
                ('estado', models.CharField(choices=[('NoIniciada', 'No Iniciada'), ('Iniciada', 'Iniciada'), ('Finalizada', 'Finalizada')], default='NoIniciada', max_length=20)),
                ('hora_medica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hora_medica_consultas', to='A20_Hrs.horamedica')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['hora_medica'],
            },
        ),
        migrations.CreateModel(
            name='Consulta_Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('lugar_emision', models.CharField(help_text='Lugar de emisión', max_length=100)),
                ('dirigido_a', models.CharField(help_text='Dirigido a', max_length=100)),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes clínicos', null=True)),
                ('diagnosis', models.TextField(blank=True, help_text='Diagnóstico', null=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones', null=True)),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
                ('archivo', models.FileField(upload_to='Certificados')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_certificados', to='A31_Con.consulta')),
            ],
            options={
                'verbose_name': 'Consulta Certificado',
                'verbose_name_plural': 'Consultas Certificados',
                'ordering': ['consulta'],
            },
        ),
        migrations.CreateModel(
            name='Consulta_imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_imagenes', to='A31_Con.consulta')),
            ],
            options={
                'verbose_name': 'Consulta Imagen',
                'verbose_name_plural': 'Consultas Imagenes',
                'ordering': ['consulta'],
            },
        ),
        migrations.CreateModel(
            name='Consulta_Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='Examenes')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('subido', 'Subido'), ('anulado', 'Anulado')], default='solicitado', max_length=20)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_examenes', to='A31_Con.consulta')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_consultas', to='A31_Con.examen')),
            ],
            options={
                'verbose_name': 'Consulta Examen',
                'verbose_name_plural': 'Consultas Examenes',
                'ordering': ['consulta'],
            },
        ),
        migrations.CreateModel(
            name='Consulta_Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(help_text='Vía de administración', max_length=100)),
                ('dosis', models.CharField(help_text='Dosis a administrar', max_length=100)),
                ('frecuencia', models.CharField(help_text='Frecuencia de administración', max_length=100)),
                ('duracion', models.CharField(help_text='Duración del tratamiento', max_length=100)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_recetas', to='A31_Con.consulta')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicamento_consultas', to='A31_Con.medicamento')),
            ],
            options={
                'verbose_name': 'Consulta Receta',
                'verbose_name_plural': 'Consultas Recetas',
                'ordering': ['consulta'],
            },
        ),
    ]
