# Generated by Django 5.1.4 on 2025-02-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='laboratorio',
            field=models.CharField(blank=True, help_text='Laboratorio', max_length=100, null=True),
        ),
    ]
