# Generated by Django 5.1.4 on 2025-02-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0003_consulta_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta_certificado',
            name='email_empleador',
            field=models.EmailField(blank=True, default='Sin data', max_length=254, null=True),
        ),
    ]
