# Generated by Django 5.1.4 on 2025-03-07 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0004_consulta_certificado_email_empleador'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='had_Certificado',
            field=models.BooleanField(default=False, help_text='¿Se ha emitido algún certificado?'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='had_OrdExams',
            field=models.BooleanField(default=False, help_text='¿Se han solicitado exámenes?'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='had_Receta',
            field=models.BooleanField(default=False, help_text='¿Se ha recetado algún medicamento?'),
        ),
        migrations.CreateModel(
            name='Consulta_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_exam', models.FileField(blank=True, null=True, upload_to='Docs_Exams/')),
                ('notas_exams', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_docs', to='A31_Con.consulta')),
            ],
            options={
                'verbose_name': 'Resultado de exámen',
                'verbose_name_plural': 'Resultado de Exámenes',
                'ordering': ['consulta'],
            },
        ),
    ]
