# Generated by Django 5.1.4 on 2025-03-24 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0005_consulta_had_certificado_consulta_had_ordexams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='resultados_enviados',
            field=models.BooleanField(default=False, help_text='¿Se han enviado los resultados al médico?'),
        ),
    ]
