# Generated by Django 5.1.4 on 2025-03-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0006_consulta_resultados_enviados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta_certificado',
            name='email_empleador',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_certificado',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_certificado',
            name='termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
