# Generated by Django 5.1.4 on 2025-03-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A31_Con', '0007_alter_consulta_certificado_email_empleador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta_certificado',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='Certificados'),
        ),
        migrations.AlterField(
            model_name='consulta_certificado',
            name='dirigido_a',
            field=models.CharField(blank=True, help_text='Dirigido a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta_certificado',
            name='lugar_emision',
            field=models.CharField(blank=True, help_text='Lugar de emisión', max_length=100, null=True),
        ),
    ]
